//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_IoTData.cpp
//  Source: ../../idl/dds_IoTData.idl
//  Generated: Tue Dec 19 20:00:37 2017
//  OpenSplice 6.8.3
//  
//******************************************************************

#include "dds_IoTData.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < DDS::IoT::IoTNVP, struct IoTNVPSeq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::IoT::IoTCh, struct IoTChSeq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < DDS::IoT::IoTStr, struct IoTStrSeq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::IoT::IoTB, struct IoTBSeq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::IoT::IoTF64, struct IoTF64Seq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::IoT::IoTF32, struct IoTF32Seq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::IoT::IoTI64, struct IoTI64Seq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::IoT::IoTI32, struct IoTI32Seq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::IoT::IoTI16, struct IoTI16Seq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::IoT::IoTI8, struct IoTI8Seq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::IoT::IoTUI64, struct IoTUI64Seq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::IoT::IoTUI32, struct IoTUI32Seq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::IoT::IoTUI16, struct IoTUI16Seq_uniq_>;
#endif
#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUFLSeq < DDS::IoT::IoTUI8, struct IoTUI8Seq_uniq_>;
#endif



