//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ListenerData.h
//  Source: ../../idl/ListenerData.idl
//  Generated: Tue Dec 19 20:04:59 2017
//  OpenSplice 6.8.3
//  
//******************************************************************
#ifndef _LISTENERDATA_H_
#define _LISTENERDATA_H_

#include "sacpp_mapping.h"


namespace ListenerData
{
   struct Msg;

   struct Msg
   {
         DDS::Long userID;
         DDS::String_mgr message;
   };

   typedef DDS_DCPSStruct_var < Msg> Msg_var;
   typedef DDS_DCPSStruct_out < Msg> Msg_out;
}




#endif
